#!/bin/sh
# Regenerate HASH_TYPES.md from the hashpipe binary.
#
# The table is GENERATED, never hand-edited and never parsed out of
# hashpipe.c. hashpipe -N prints one row per type -- index, name, hashcat
# modes, flags, self-test vector -- applying the same rendering rules the
# binary uses internally. Parsing the HT() macros from source cannot be made
# reliable: rules like HTF_UC are applied at render time, so an external
# parser has to reimplement them and quietly gets the rest wrong.
#
# hashpipe -T verifies every vector in the table, so -T passing is proof that
# every row emitted here is correct for this build.
#
# Usage: ./gen-hash-types.sh [path-to-hashpipe] > HASH_TYPES.md
set -e
HP="${1:-hashpipe}"
command -v "$HP" >/dev/null 2>&1 || [ -x "$HP" ] || { echo "no hashpipe at $HP" >&2; exit 1; }

TSV=$(mktemp); trap 'rm -f "$TSV"' EXIT
"$HP" -N > "$TSV"

VER=$(sed -n 's/^# .*hashpipe\.c,v \([0-9.]*\).*/\1/p' "$TSV" | head -1)
NTYPES=$(grep -vc '^#' "$TSV")
NOVEC=$(awk -F'\t' '!/^#/ && $5==""' "$TSV" | wc -l | tr -d ' ')

cat <<HDR
# hashpipe — Supported Hash Types

Complete list of all hash types supported by hashpipe, with internal type index,
hash name, hashcat mode mapping, and an example hash:password pair.

**$NTYPES types** as of v$VER.

Each example is the complete self-test vector from \`hashpipe -T\`, shown as
\`hash[:salt]:password\` — the same format hashpipe accepts as input.
Every vector here passes its self-test in this build; nothing is listed
that does not currently verify.

HDR

if [ "$NOVEC" -gt 0 ]; then
cat <<HDR2
$NOVEC types share a compute function with another type and carry no
dedicated self-test vector; they are still fully functional.

HDR2
fi

cat <<HDR3
The house test password is \`password123\`. A few types cannot use it by
construction — DES crypt and the SAP BCODE, AS/400 and RACF KDFAES
families truncate the password to 8 bytes, so those use \`pass1234\` or
\`password\`, and WPA-PMK takes a 32-byte key rather than a password.

This file is generated by \`gen-hash-types.sh\`, which reads \`hashpipe -N\`.
Do not edit it by hand; regenerate it.

## Type List

| Index | Name | Hashcat Mode | Example (hash:password) |
|-------|------|-------------|------------------------|
HDR3

awk -F'\t' '!/^#/ {
    v = $5
    if (v == "") printf "| %s | %s | %s | (shares a compute function; no dedicated vector) |\n", $1, $2, $3
    else         printf "| %s | %s | %s | `%s` |\n", $1, $2, $3, v
}' "$TSV"
